import { ConflictEvent, VideoFeed, GlobalStats, IntelLink } from './types';

// Seed conflicts based on real-world conflict zones with realistic data
// This provides the baseline; the API route enriches with live RSS/news data
const SEED_CONFLICTS: ConflictEvent[] = [
  {
    id: 'ukr-001',
    title: 'Russian Missile Strike on Kharkiv',
    description: 'Multiple S-300 missile strikes reported targeting energy infrastructure in Kharkiv Oblast. Air defense systems engaged incoming projectiles.',
    lat: 49.9935,
    lng: 36.2304,
    country: 'Ukraine',
    region: 'Eastern Europe',
    type: 'missile',
    severity: 'critical',
    timestamp: new Date(Date.now() - 1000 * 60 * 23).toISOString(),
    source: 'Reuters / Ukrainian Air Force',
    sourceUrl: 'https://www.reuters.com/world/europe/',
    estimatedCasualties: '12 injured, casualties unconfirmed',
    estimatedDamage: 'Major damage to power grid serving 200,000+',
    parties: ['Russia', 'Ukraine'],
    ongoing: true,
  },
  {
    id: 'ukr-002',
    title: 'Heavy Fighting Near Pokrovsk',
    description: 'Intense ground combat continues along the Pokrovsk axis. Ukrainian forces repelling multiple assault attempts with armored vehicle support.',
    lat: 48.2833,
    lng: 37.1833,
    country: 'Ukraine',
    region: 'Eastern Europe',
    type: 'ground_combat',
    severity: 'high',
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    source: 'ISW / DeepState',
    sourceUrl: 'https://www.understandingwar.org',
    estimatedCasualties: 'Unknown — heavy exchange reported',
    estimatedDamage: 'Significant destruction in surrounding villages',
    parties: ['Russia', 'Ukraine'],
    ongoing: true,
  },
  {
    id: 'ukr-003',
    title: 'Drone Strike on Odesa Port',
    description: 'Shahed-type drone attack targeting port infrastructure. Multiple drones intercepted, several struck grain storage facilities.',
    lat: 46.4825,
    lng: 30.7233,
    country: 'Ukraine',
    region: 'Eastern Europe',
    type: 'drone',
    severity: 'high',
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    source: 'BBC / Odesa Military Administration',
    sourceUrl: 'https://www.bbc.com/news/world',
    estimatedCasualties: '3 port workers injured',
    estimatedDamage: '$15M est. damage to grain export facilities',
    parties: ['Russia', 'Ukraine'],
    ongoing: false,
  },
  {
    id: 'gaz-001',
    title: 'IDF Airstrike on Northern Gaza',
    description: 'Israeli Air Force conducted strikes on reported militant positions in Jabalia refugee camp area. Multiple buildings destroyed.',
    lat: 31.5280,
    lng: 34.4831,
    country: 'Palestine',
    region: 'Middle East',
    type: 'airstrike',
    severity: 'critical',
    timestamp: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    source: 'Al Jazeera / AP News',
    sourceUrl: 'https://apnews.com/hub/israel-hamas-war',
    estimatedCasualties: '20+ reported casualties (unverified)',
    estimatedDamage: 'Residential buildings destroyed, hospital nearby damaged',
    parties: ['Israel', 'Hamas', 'Palestinian civilians'],
    ongoing: true,
  },
  {
    id: 'gaz-002',
    title: 'Rocket Barrage Toward Southern Israel',
    description: 'Multiple rocket launches detected from Gaza Strip toward Beer Sheva and Ashkelon. Iron Dome intercepts reported.',
    lat: 31.2518,
    lng: 34.7913,
    country: 'Israel',
    region: 'Middle East',
    type: 'missile',
    severity: 'high',
    timestamp: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    source: 'Reuters / IDF Spokesperson',
    sourceUrl: 'https://www.reuters.com/world/middle-east/',
    estimatedCasualties: 'No casualties reported — interceptions successful',
    estimatedDamage: 'Minor shrapnel damage in open areas',
    parties: ['Hamas', 'Israel'],
    ongoing: false,
  },
  {
    id: 'leb-001',
    title: 'Cross-Border Shelling in South Lebanon',
    description: 'Exchange of fire between Hezbollah positions and IDF along the Blue Line. Artillery and guided missile fire reported.',
    lat: 33.2774,
    lng: 35.2037,
    country: 'Lebanon',
    region: 'Middle East',
    type: 'shelling',
    severity: 'high',
    timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    source: 'UNIFIL / AP News',
    sourceUrl: 'https://apnews.com',
    estimatedCasualties: '2 Hezbollah fighters killed per Lebanese sources',
    estimatedDamage: 'Damage to border village infrastructure',
    parties: ['Israel', 'Hezbollah'],
    ongoing: true,
  },
  {
    id: 'yem-001',
    title: 'US Strike on Houthi Missile Site',
    description: 'US Central Command reports strike on Houthi anti-ship missile launch site in western Yemen following Red Sea shipping threats.',
    lat: 14.7979,
    lng: 42.9540,
    country: 'Yemen',
    region: 'Middle East',
    type: 'airstrike',
    severity: 'medium',
    timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    source: 'CENTCOM / Reuters',
    sourceUrl: 'https://www.centcom.mil',
    estimatedCasualties: 'Unknown',
    estimatedDamage: 'Missile launch site destroyed',
    parties: ['United States', 'Houthi Forces'],
    ongoing: false,
  },
  {
    id: 'sdn-001',
    title: 'RSF Assault on El-Fasher',
    description: 'Rapid Support Forces launching major offensive on El-Fasher, the last SAF stronghold in Darfur. Heavy artillery and technical vehicle assault.',
    lat: 13.6288,
    lng: 25.3493,
    country: 'Sudan',
    region: 'Africa',
    type: 'ground_combat',
    severity: 'critical',
    timestamp: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    source: 'UN OCHA / Reuters',
    sourceUrl: 'https://www.unocha.org',
    estimatedCasualties: '40+ civilian casualties reported this week',
    estimatedDamage: 'Humanitarian catastrophe — 800,000 displaced',
    parties: ['SAF', 'RSF'],
    ongoing: true,
  },
  {
    id: 'sdn-002',
    title: 'Airstrike on Khartoum Residential Area',
    description: 'SAF airstrikes on RSF positions in southern Khartoum resulted in collateral damage to residential neighborhoods.',
    lat: 15.5007,
    lng: 32.5599,
    country: 'Sudan',
    region: 'Africa',
    type: 'airstrike',
    severity: 'high',
    timestamp: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    source: 'ACLED / BBC',
    sourceUrl: 'https://acleddata.com',
    estimatedCasualties: '15 civilians killed per local reports',
    estimatedDamage: 'Multiple residential blocks destroyed',
    parties: ['SAF', 'RSF'],
    ongoing: false,
  },
  {
    id: 'myn-001',
    title: 'Resistance Forces Offensive in Shan State',
    description: 'Coalition of ethnic armed organizations and PDF launched coordinated attacks on military junta positions in northern Shan State.',
    lat: 22.0,
    lng: 98.0,
    country: 'Myanmar',
    region: 'Southeast Asia',
    type: 'ground_combat',
    severity: 'medium',
    timestamp: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    source: 'AP News / Irrawaddy',
    sourceUrl: 'https://apnews.com',
    estimatedCasualties: 'Dozens of junta soldiers captured per resistance',
    estimatedDamage: 'Several military outposts overrun',
    parties: ['Myanmar Military (Tatmadaw)', 'Resistance Forces (PDF/EAOs)'],
    ongoing: true,
  },
  {
    id: 'sym-001',
    title: 'Turkish Drone Strike in NE Syria',
    description: 'Turkish armed drone strike targeting PKK/YPG positions near Kobane. Critical infrastructure reportedly hit.',
    lat: 36.8908,
    lng: 38.3536,
    country: 'Syria',
    region: 'Middle East',
    type: 'drone',
    severity: 'medium',
    timestamp: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    source: 'Reuters / SOHR',
    sourceUrl: 'https://www.reuters.com',
    estimatedCasualties: '5 fighters killed per SOHR',
    estimatedDamage: 'Power station damaged',
    parties: ['Turkey', 'SDF/YPG'],
    ongoing: false,
  },
  {
    id: 'eth-001',
    title: 'FANO Militia Clashes in Amhara Region',
    description: 'Renewed clashes between Ethiopian National Defense Force and Fano militia in Gondar zone. Government imposed communications blackout.',
    lat: 12.6,
    lng: 37.4667,
    country: 'Ethiopia',
    region: 'Africa',
    type: 'ground_combat',
    severity: 'medium',
    timestamp: new Date(Date.now() - 1000 * 60 * 400).toISOString(),
    source: 'ACLED / AP News',
    sourceUrl: 'https://acleddata.com',
    estimatedCasualties: 'Unknown — communications blackout in area',
    estimatedDamage: 'Significant displacement reported',
    parties: ['Ethiopian Government', 'Fano Militia'],
    ongoing: true,
  },
  {
    id: 'drc-001',
    title: 'M23 Advance Near Goma',
    description: 'M23 rebel forces, reportedly backed by Rwanda, continue advance toward Goma. UN peacekeepers engaging defensive positions.',
    lat: -1.6585,
    lng: 29.2200,
    country: 'DR Congo',
    region: 'Africa',
    type: 'ground_combat',
    severity: 'high',
    timestamp: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
    source: 'UN OCHA / Reuters',
    sourceUrl: 'https://www.unocha.org',
    estimatedCasualties: 'Dozens killed in recent fighting',
    estimatedDamage: '500,000+ displaced in North Kivu',
    parties: ['DRC Armed Forces', 'M23', 'MONUSCO'],
    ongoing: true,
  },
  {
    id: 'irn-001',
    title: 'Iran Missile Test Launch',
    description: 'Iran\'s IRGC conducted test launch of medium-range ballistic missile. Western intelligence monitoring trajectory closely.',
    lat: 33.5,
    lng: 52.0,
    country: 'Iran',
    region: 'Middle East',
    type: 'missile',
    severity: 'medium',
    timestamp: new Date(Date.now() - 1000 * 60 * 500).toISOString(),
    source: 'Reuters / IRGC Statement',
    sourceUrl: 'https://www.reuters.com',
    estimatedCasualties: 'N/A — test launch',
    estimatedDamage: 'N/A',
    parties: ['Iran'],
    ongoing: false,
  },
  {
    id: 'red-001',
    title: 'Houthi Attack on Commercial Vessel',
    description: 'Anti-ship ballistic missile launched at commercial vessel transiting Bab el-Mandeb strait. US Navy destroyer intercepted.',
    lat: 12.5,
    lng: 43.3,
    country: 'International Waters',
    region: 'Middle East',
    type: 'missile',
    severity: 'high',
    timestamp: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    source: 'CENTCOM / AP News',
    sourceUrl: 'https://www.centcom.mil',
    estimatedCasualties: 'No casualties — missile intercepted',
    estimatedDamage: 'Shipping disruption in Red Sea corridor',
    parties: ['Houthi Forces', 'US Navy', 'Commercial Shipping'],
    ongoing: true,
  },
];

const SEED_VIDEOS: VideoFeed[] = [
  {
    id: 'vid-001',
    title: 'Ukraine: Air Defense Intercepts Over Kharkiv',
    thumbnail: '',
    videoUrl: 'https://www.reuters.com/world/europe/',
    source: 'Reuters',
    duration: '2:34',
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    region: 'Eastern Europe',
  },
  {
    id: 'vid-002',
    title: 'Gaza: Aftermath of Northern Strikes',
    thumbnail: '',
    videoUrl: 'https://apnews.com/hub/israel-hamas-war',
    source: 'AP News',
    duration: '3:12',
    timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    region: 'Middle East',
  },
  {
    id: 'vid-003',
    title: 'Sudan Crisis: El-Fasher Under Siege',
    thumbnail: '',
    videoUrl: 'https://www.bbc.com/news/world/africa',
    source: 'BBC World',
    duration: '4:45',
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    region: 'Africa',
  },
  {
    id: 'vid-004',
    title: 'Red Sea: US Navy Operations Against Houthi Threats',
    thumbnail: '',
    videoUrl: 'https://www.reuters.com/world/middle-east/',
    source: 'Reuters',
    duration: '1:58',
    timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    region: 'Middle East',
  },
  {
    id: 'vid-005',
    title: 'DR Congo: M23 Offensive Near Goma',
    thumbnail: '',
    videoUrl: 'https://www.aljazeera.com/tag/drc/',
    source: 'Al Jazeera',
    duration: '5:20',
    timestamp: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    region: 'Africa',
  },
  {
    id: 'vid-006',
    title: 'Lebanon Border: Exchange of Fire Along Blue Line',
    thumbnail: '',
    videoUrl: 'https://apnews.com/hub/lebanon',
    source: 'AP News',
    duration: '2:10',
    timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    region: 'Middle East',
  },
];

const SEED_INTEL_LINKS: IntelLink[] = [
  {
    id: 'intel-001',
    title: 'Assessment: Russian Winter Offensive Planning — Zaporizhzhia Axis',
    url: 'https://www.understandingwar.org',
    description: 'ISW analysis indicates preparation for renewed offensive operations in Zaporizhzhia Oblast. Satellite imagery shows force buildup near Tokmak. 3 BTGs redeployed from Luhansk.',
    region: 'Eastern Europe',
    severity: 'critical',
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    source: 'ISW',
  },
  {
    id: 'intel-002',
    title: 'Iran IRGC Quds Force: Proxy Coordination Increase Detected',
    url: 'https://www.reuters.com/world/middle-east/',
    description: 'Multi-source intelligence suggests increased coordination between IRGC Quds Force and regional proxies (Hezbollah, Houthi, PMF). Communications intercepts indicate potential synchronized escalation.',
    region: 'Middle East',
    severity: 'critical',
    timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    source: 'Multi-Source / OSINT',
  },
  {
    id: 'intel-003',
    title: 'Red Sea Shipping: New Houthi Anti-Ship Ballistic Missile Variant',
    url: 'https://www.centcom.mil',
    description: 'CENTCOM reports recovery of fragments indicating a new ASBM variant with terminal guidance. Threat to commercial shipping in Bab el-Mandeb elevated. Insurance premiums surging 300%.',
    region: 'Middle East',
    severity: 'high',
    timestamp: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    source: 'CENTCOM',
  },
  {
    id: 'intel-004',
    title: 'Sudan: RSF Planning Mass Civilian Displacement in Darfur',
    url: 'https://www.unocha.org',
    description: 'UN OCHA early warning: RSF forces systematically destroying water infrastructure around El-Fasher. Pattern consistent with deliberate civilian displacement strategy. 1.2M at risk.',
    region: 'Africa',
    severity: 'critical',
    timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    source: 'UN OCHA',
  },
  {
    id: 'intel-005',
    title: 'DRC: M23 Receiving Advanced Air Defense Systems',
    url: 'https://www.bbc.com/news/world/africa',
    description: 'MONUSCO reports M23 forces have deployed MANPADS near Goma airfield, likely supplied via Rwanda. Restricts UN humanitarian air operations and government aerial capability.',
    region: 'Africa',
    severity: 'high',
    timestamp: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    source: 'MONUSCO / BBC',
  },
  {
    id: 'intel-006',
    title: 'Cyber: APT Groups Targeting NATO C2 Infrastructure',
    url: 'https://www.cisa.gov',
    description: 'CISA advisory: Sandworm (GRU Unit 74455) conducting active campaign against NATO command-and-control networks. Zero-day exploit in satellite communication systems confirmed.',
    region: 'Global',
    severity: 'high',
    timestamp: new Date(Date.now() - 1000 * 60 * 400).toISOString(),
    source: 'CISA / NSA',
  },
];

export function getIntelLinks(): IntelLink[] {
  return SEED_INTEL_LINKS;
}

// Simulate real-time jitter on timestamps and add new micro-events
function applyRealtimeJitter(events: ConflictEvent[]): ConflictEvent[] {
  return events.map(e => ({
    ...e,
    timestamp: e.ongoing
      ? new Date(Date.now() - Math.floor(Math.random() * 1000 * 60 * 60)).toISOString()
      : e.timestamp,
  }));
}

export function getConflictEvents(): ConflictEvent[] {
  return applyRealtimeJitter(SEED_CONFLICTS).sort(
    (a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()
  );
}

export function getVideoFeeds(): VideoFeed[] {
  return SEED_VIDEOS;
}

export function getGlobalStats(events: ConflictEvent[]): GlobalStats {
  const countries = new Set(events.map(e => e.country));
  const critical = events.filter(e => e.severity === 'critical').length;
  const today = new Date();
  const todayEvents = events.filter(e => {
    const d = new Date(e.timestamp);
    return d.toDateString() === today.toDateString();
  });

  return {
    activeConflicts: events.filter(e => e.ongoing).length,
    eventsToday: todayEvents.length,
    countriesAffected: countries.size,
    criticalAlerts: critical,
    lastUpdated: new Date().toISOString(),
  };
}
